name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # ✅ Step 1: Install Salesforce CLI
      - name: Install Salesforce CLI
        run: npm install --global sfdx-cli

      # ✅ Step 2: Authenticate using your secret SFDX_AUTH_URL
      - name: Authenticate to Salesforce
        run: echo ${{ secrets.SFDX_AUTH_URL }} | sf org login sfdx-url --sfdx-url-stdin --alias my-org --set-default

      # ✅ Step 3: Deploy Metadata
      - name: Deploy metadata
        run: sf project deploy start --manifest manifest/package/package.xml --target-org my-org
