name: Delta Deploy to Salesforce

on:
  push:
    branches:
      - main
      - feature/**

jobs:
  delta-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli
          npm install --global sfdx-cli

      - name: Install sfdx-git-delta
        run: |
          sf plugins install sfdx-git-delta

      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > auth.txt
          sf org login sfdx-url --sfdx-url-file auth.txt --alias my-org --set-default
          rm auth.txt

      - name: Generate delta using sgd
        run: |
          mkdir -p manifest/package
          sfdx sgd:source:delta --to main --from HEAD~1 --output manifest

      - name: Deploy delta to Salesforce
        run: |
          if [ -f "manifest/package/package.xml" ]; then
            sf project deploy start --manifest manifest/package/package.xml --ignore-conflicts --wait 10
          else
            echo "No changes to deploy"
          fi
