name: Deploy to Salesforce

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Salesforce CLI (sfdx)
        run: npm install -g sfdx-cli

      - name: Authenticate to Salesforce
        run: echo "${{ secrets.SFDX_AUTH_URL }}" | sfdx auth:sfdxurl:store --sfdxurlstdin --setalias my-org --setdefaultusername

      - name: Deploy Metadata
        run: sfdx force:source:deploy -x manifest/package.xml
