name: Deploy to Salesforce

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # ✅ Install the modern Salesforce CLI (sf)
      - name: Install Salesforce CLI
        uses: salesforcecli/sfdx-github-action@v1

      # ✅ Authenticate using SFDX Auth URL
      - name: Authenticate to Salesforce
        run: echo "${{ secrets.SFDX_AUTH_URL }}" | sf org login sfdx-url --sfdx-url-stdin --alias my-org --set-default

      # ✅ Deploy metadata using manifest
      - name: Deploy Metadata
        run: sf project deploy start --manifest manifest/package.xml
