name: Deploy to Salesforce

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Salesforce CLI (sfdx)
        run: |
          npm install --global sfdx-cli
          sfdx --version

      - name: Install sfdx-git-delta plugin
        run: sfdx plugins:install sfdx-git-delta

      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > auth.txt
          sfdx auth:sfdxurl:store --sfdxurlfile auth.txt --setdefaultusername --setalias my-org
          rm auth.txt

      - name: Generate delta using sgd
        run: |
          sfdx sgd:source:delta --to main --from HEAD~1 --output manifest

      - name: Deploy delta metadata
        run: |
          if [ -f manifest/package/package.xml ]; then
            sfdx force:source:deploy -x manifest/package/package.xml --wait 10
          else
            echo "No metadata changes to deploy"
          fi

      - name: Deploy destructive changes (if any)
        run: |
          if [ -f manifest/destructiveChanges/destructiveChanges.xml ]; then
            sfdx force:source:deploy -x manifest/destructiveChanges/destructiveChanges.xml --wait 10
          else
            echo "No destructive changes to deploy"
          fi
