name: Deploy to Salesforce

on:
  push:
    branches:
      - main
      - feature/**

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli
          sf --version
          sfdx --version

      - name: Install sfdx-git-delta plugin
        run: sfdx plugins:install sfdx-git-delta --yes

      - name: Authenticate to Salesforce
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > auth.txt
          sf org login sfdx-url --sfdx-url-file auth.txt --alias my-org --set-default
          rm auth.txt

      - name: Generate delta using sgd
        run: |
          sfdx sgd:source:delta --to "${{ github.ref_name }}" --from main --output manifest

      - name: Deploy delta metadata
        run: |
          if [ -f manifest/package/package.xml ]; then
            sf project deploy start \
              --manifest manifest/package/package.xml \
              --wait 10
          else
            echo "No metadata changes to deploy"
          fi

      - name: Deploy destructive changes (if any)
        run: |
          if [ -f manifest/destructiveChanges/destructiveChanges.xml ]; then
            sf project deploy start \
              --manifest manifest/destructiveChanges/destructiveChanges.xml \
              --wait 10
          else
            echo "No destructive changes to deploy"
          fi
