name: Deploy to Salesforce

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Salesforce CLI
        run: |
          npm install --global @salesforce/cli
          sf --version

      - name: Install sfdx-git-delta plugin
        run: sf plugins install sfdx-git-delta

      - name: Authenticate to Salesforce
        shell: bash
        run: |
          echo "${{ secrets.SFDX_AUTH_URL }}" > auth.txt
          sf org login sfdx-url --sfdx-url-file auth.txt --alias my-org --set-default
          rm auth.txt

      - name: Generate delta using sgd
        run: |
          mkdir -p manifest/package
          sf sgd source delta --to feature/lwc-change --from main --output-dir manifest

      - name: Deploy delta to Salesforce
        run: |
          if [ -f "manifest/package/package.xml" ]; then
            sf project deploy start --manifest manifest/package/package.xml --ignore-conflicts --wait 10
          else
            echo "No changes to deploy"
          fi
